# Generated by Django 5.2.5 on 2025-08-13 14:16

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_created_at_client_is_active_client_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Property Type of Service',
                'verbose_name_plural': 'Property Type of Services',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='contract_start_date',
            field=models.DateField(null=True, verbose_name='Contract Start Date'),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Rate'),
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='property',
            name='types_of_service',
            field=models.ManyToManyField(related_name='properties', to='core.propertytypeofservice', verbose_name='Types of Service'),
        ),
    ]
