# Generated by Django 5.2.5 on 2025-08-13 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propertytypeofservice_property_contract_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='guard',
            name='ssn',
            field=models.CharField(blank=True, max_length=20, verbose_name='SSN'),
        ),
        migrations.CreateModel(
            name='GuardPropertyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rate per Hour')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tariffs', to='core.guard', verbose_name='Guard')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_tariffs', to='core.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Guard Property Tariff',
                'verbose_name_plural': 'Guard Property Tariffs',
                'constraints': [models.UniqueConstraint(fields=('guard', 'property'), name='unique_guard_property_tariff')],
            },
        ),
    ]
