# Generated by Django 5.2.5 on 2025-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guard_address_guard_ssn_guardpropertytariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('voided', 'Voided')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
    ]
