# Generated by Django 5.2.5 on 2025-08-15 14:44
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_shift_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="alias",
            field=models.CharField(
                max_length=255, verbose_name="Alias", null=True, blank=True
            ),
        ),
    ]
