# Generated by Django 5.2.5 on 2025-08-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_managers_alter_expense_managers_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guardpropertytariff',
            name='unique_guard_property_tariff',
        ),
        migrations.AddField(
            model_name='guard',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AddConstraint(
            model_name='guardpropertytariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('guard', 'property'), name='unique_active_guard_property_tariff'),
        ),
    ]
