# Generated by Django 5.2.5 on 2025-09-03 13:09

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_property_monthly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial Number')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='core.guard', verbose_name='Guard')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
                'unique_together': {('guard', 'serial_number')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
