# Generated by Django 5.2.5 on 2025-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='is_armed',
            field=models.BooleanField(default=False, verbose_name='Is armed'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_armed',
            field=models.BooleanField(default=False, verbose_name='Is Armed'),
        ),
    ]
