# Generated by Django 5.2.5 on 2025-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contract_start_date',
        ),
        migrations.AddField(
            model_name='service',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract Start Date'),
        ),
    ]
