# Generated by Django 5.2.5 on 2025-08-17 18:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='generalsettings',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
