# Generated by Django 5.2.5 on 2025-08-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_generalsettings_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='api_page_size',
            field=models.PositiveIntegerField(default=20, help_text='Number of items per page across the API', verbose_name='API Page Size'),
        ),
    ]
