# Generated by Django 5.2.5 on 2025-08-11 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('client', 'Client'), ('guard', 'Guard'), ('supervisor', 'Supervisor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'permissions': [('manage_user_roles', 'Can manage user roles'), ('view_all_roles', 'Can view all user roles')],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(max_length=50)),
                ('permission_details', models.JSONField()),
                ('action', models.CharField(choices=[('granted', 'Permission Granted'), ('revoked', 'Permission Revoked'), ('modified', 'Permission Modified'), ('expired', 'Permission Expired')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_permission_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Log',
                'verbose_name_plural': 'Permission Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='permissions_user_id_412034_idx'), models.Index(fields=['performed_by', 'timestamp'], name='permissions_perform_9f8ad4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('owner', 'Owner'), ('assigned_guard', 'Assigned Guard'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer')], max_length=20)),
                ('can_create_shifts', models.BooleanField(default=False)),
                ('can_edit_shifts', models.BooleanField(default=False)),
                ('can_create_expenses', models.BooleanField(default=False)),
                ('can_edit_expenses', models.BooleanField(default=False)),
                ('can_approve_expenses', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_property_access', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Access',
                'verbose_name_plural': 'Property Access',
                'indexes': [models.Index(fields=['user', 'property'], name='permissions_user_id_d4805e_idx'), models.Index(fields=['property', 'access_type'], name='permissions_propert_299314_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('property', 'Property'), ('shift', 'Shift'), ('expense', 'Expense'), ('guard', 'Guard'), ('client', 'Client')], max_length=20)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('assign', 'Assign')], max_length=10)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Permission',
                'verbose_name_plural': 'Resource Permissions',
                'indexes': [models.Index(fields=['user', 'resource_type', 'action'], name='permissions_user_id_8317c6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='permissions_resourc_2dcfe2_idx')],
                'unique_together': {('user', 'resource_type', 'action', 'resource_id')},
            },
        ),
    ]
