# Generated by Django 5.2.5 on 2025-08-17 18:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_permissionlog_created_at_permissionlog_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permissionlog',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='propertyaccess',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resourcepermission',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userrole',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
