# Generated by Django 5.2.5 on 2025-09-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permissionlog_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepermission',
            name='resource_type',
            field=models.CharField(choices=[('property', 'Property'), ('shift', 'Shift'), ('expense', 'Expense'), ('guard', 'Guard'), ('client', 'Client'), ('service', 'Service')], max_length=20),
        ),
    ]
